---
- name: Install Ansible Docker dependencies
  apt:
    name: python3-docker
    state: present

- name: Install Docker
  apt:
    name: docker.io
    state: present

- name: Ensure Docker is running and will run
  service:
    name: docker
    state: started
    enabled: yes
