---
- name: Ensure ufw is installed
  apt:
    name: ufw
    state: present

- include: ports.yaml

# UFW has it's own service management layer. So no service module needed
- name: Start the ufw service
  ufw:
    state: enabled

- name: setup default outgoing rule
  ufw:
    rule: allow
    direction: out

- name: setup default outgoing rule
  ufw:
    rule: allow
    direction: out

- name: Limit number of SSH connections
  ufw:
    rule: limit
    port: ssh
    proto: tcp

- name: Allow SSH access
  ufw:
    rule: allow
    name: OpenSSH

- name: set default incoming rule
  ufw:
    rule: deny
    direction: in
