---
- name: Make jellyfin config directories
  file:
    path: "{{ item }}"
    state: directory
    recurse: yes
  loop:
    - "{{ jellyfin_base_path }}"
    - "{{ jellyfin_config_path }}"
    - "{{ jellyfin_config_system_path }}"
    - "{{ jellyfin_cache_path }}"

- name: Copy over jellifin default config
  copy:
    src: jellyfin/system.xml
    dest: "{{ jellyfin_config_system_path }}/system.xml"
    force: no

- name: Create jellyfin configuration for nginx
  template:
    src: nginx/jellyfin.conf.j2
    dest: "{{ nginx_config_webgateway_path }}/jellyfin.conf"

- name: Install Jellyfin image
  docker_container:
    name: jellyfin
    image: "jellyfin/jellyfin:{{ jellyfin_version }}"
    state: started
    restart: yes
    volumes:
      - "{{ jellyfin_config_path }}:{{ jellyfin_config_volume_path }}"
      - "{{ jellyfin_cache_path }}:{{ jellyfin_cache_volume_path }}"
    mounts:
      - type: bind
        read_only: yes
        source: "{{ rclone_mount_directory_path }}"
        target: /media/b2/matt
      - type: bind
        read_only: yes
        source: "{{ ftp_rar_mount_directory_path }}"
        target: /media/ftp/eagle

- name: Connect to web gateway network to communicate with nginx
  community.docker.docker_network:
    name: "{{ webgateway_network_name }}"
    connected:
      - jellyfin
    appends: yes
  notify:
    - Restart Nginx
