---
- include_tasks: apt.yml
- include_tasks: disks.yml
  when: not testing
- include_tasks: auditd.yml
- include_tasks: apparmor.yml
# disabled while spiking because it's slow to run
#include_role: devsec.hardening.os_hardening
- include_tasks: timesync.yml
  when: not testing
- include_tasks: cagent.yml
- include_tasks: firewall.yml

- include_tasks: docker.yml
- include_tasks: nginx.yml
#- include_tasks: certbot.yml
#- include_tasks: jellyfin.yml
#- include_tasks: nextcloud.yml
