---
- name: Create directories for rclone
  file:
    path: "{{ item }}"
    state: directory
    recurse: yes
  loop:
    - "{{ rclone_mount_directory_path }}"
    - "{{ rclone_config_directory }}"
    - "{{ rclone_log_directory }}"

- name: Install rclone
  apt:
    name: rclone
    state: present

- debug:
    msg: "{{ ansible_facts }}"

- name: Create rclone config
  template:
    src: rclone/rclone.conf
    dest: "{{ rclone_config_file_path }}"

- name: Create rclone service
  template:
    src: rclone/rclone.service
    dest: /etc/systemd/system

- name: Set rclone service to run
  service:
    name: rclone
    state: started
    masked: no
    enabled: yes
