---
- name: Get secrets url
  command: "scw-userdata doppler-project-url"
  register: secret_url

- name: Get secret to access secret
  command: "scw-userdata doppler-project-secret"
  register: secret_secret

- name: Get secrets from Doppler
  ansible.builtin.uri:
    url: "{{ secret_url }}"
    method: GET
    status_code: 200
    body_format: json
    headers:
      accept: application/json
      accepts: application/json
      authorization: "Bearer {{ secret_secret }}"
  register: secrets

- name: Store secrets in facts
  set_fact:
    secrets: {{ secrets.body.secrets }}