---
- name: Get secrets url
  command:
    cmd: "scw-userdata doppler-project-url"
  register: secret_url

- name: Get secret to access secret
  command:
    cmd: "scw-userdata doppler-project-secret"
  register: secret_secret

- name: Get secrets from Doppler
  ansible.builtin.uri:
    url: "{{ secret_url.stdout }}"
    method: GET
    status_code: 200
    body_format: json
    headers:
      accept: application/json
      accepts: application/json
      authorization: "Bearer {{ secret_secret.stdout }}"
  register: secrets