---
- name: Create swap file
  command:
    cmd: "dd if=/dev/zero of={{ swap_file_path }} bs={{ ansible_memtotal_mb }} count=1048576"
    creates: "{{ swap_file_path }}"

- name: Set root ownership
  ansible.builtin.file:
    path: "{{ swap_file_path }}"
    owner: root
    group: root
    mode: '0600'

- name : Format swap
  filesystem:
    fstype: swap
    dev: "{{ swap_file_path }}"

- name: Enable swap
  command:
    cmd: "swapon {{ swap_file_path }}"
    creates: "{{ swap_file_path }}"
