---
- name: Create directories for ftp
  file:
    path: "{{ item }}"
    state: directory
    recurse: yes
  loop:
    - "{{ unrar_mount_directory_path }}"

# This part re-mounts the ftp mount and uses rar2fs the ability to invisibly un-rar any files

- name: Install ftp
  apt:
    name: libfuse2
    state: present

- name: RAR Extract
  copy:
    src: ftp/rar2fs
    dest: /usr/bin/rar2fs
    mode: '0700'

- name: Create unrar service
  template:
    src: unrar/unrar.service
    dest: /etc/systemd/system

- name: Set unrar service to run
  service:
    name: unrar
    state: started
    masked: no
    enabled: yes
  when: not testing | default('no') | bool