---
name: Ansible Role Test
on:
  - push

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install -r requirementsDev.txt
      - name: Run molecule
        run: |
          molecule dependency
          molecule lint
          molecule syntax
  test:
    runs-on: ubuntu-20.04
    env:
      ANSIBLE_ROLES_PATH: ~/
    steps:
      - uses: actions/checkout@v2
      - name: Install python3
        run: ${{ matrix.docker-instances.bootstrap }}
      - name: Install ansible
        run: python3 -m pip install -r requirementsDev.txt
      - name: Copy role to somewhere it can be found
        run: cp -r ../ansible-role-media ~/media
      - name: Run playbook
        run: ansible-playbook -i tests/inventory tests/playbook.yml --extra-vars "@tests/extra-vars.yml"
